export const HEARTBEAT_INTERVAL_MS = 30000;
export const HEARTBEAT_TIMEOUT_MS = 5000;
export const RCON_SOCKET_TIMEOUT_MS = 5000;
export const RCON_DISCONNECT_TIMEOUT_MS = 3000;
export const DEFAULT_AUTH_TIMEOUT_MS = 10000;
export const MAX_HEARTBEAT_INTERVAL_MS = 60000;
